
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-11-02T16:19:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "58d9e66e0edd46c53516482f507b740e2447b745",
 "version": "1.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
